name: buem_env
channels:
  - conda-forge
  - default
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - pvlib
  - scipy
  - sympy
  - openpyxl
  - cvxpy
  - flask
  - python-dotenv
  - pulp
  - gunicorn    # required only inside container
  - coincbc     # if you want conda solver inside container; apt-get coinor-cbc already installed too
  - pip
  - pip:
    - marshmallow>=4.0.0
    - marshmallow-dataclass>=8.0.0